version: "3.3"

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    env_file:
      - .env
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.dante.address=:2020"
      - "--certificatesresolvers.exitNode.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.exitNode.acme.email=devops@lethean.io"
      - "--certificatesresolvers.exitNode.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "80:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  authentik-proxy:
    image: ghcr.io/goauthentik/proxy
    ports:
      - 9000:9000
      - 9443:9443
    env_file:
      - .env
    environment:
      AUTHENTIK_HOST: https://${AUTH_HOSTNAME}
      AUTHENTIK_INSECURE: "false"
      AUTHENTIK_TOKEN: qilbRpXKmXlgDYQZUsL6EiyhsMocyT4vQ0rP9bFL
      # Starting with 2021.9, you can optionally set this too
      # when authentik_host for internal communication doesn't match the public URL
      # AUTHENTIK_HOST_BROWSER: https://external-domain.tld
    labels:
      traefik.enable: true
      traefik.port: 9000
      traefik.http.routers.authentik.rule: HostRegexp(`${SERVER_CNAME_NAMESPACE}`, `{subdomain:[a-z]+}.${SERVER_CNAME_NAMESPACE}`) && PathPrefix(`/outpost.goauthentik.io/`)
      # `authentik-proxy` refers to the service name in the compose file.
      traefik.http.middlewares.authentik.forwardauth.address: https://${AUTH_HOSTNAME}/outpost.goauthentik.io/auth/traefik
      traefik.http.middlewares.authentik.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authentik.forwardauth.authResponseHeaders: X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version
    restart: unless-stopped

  dante:
    image: "lthn/dante:next"
    container_name: "proxy-socks-dante"
    volumes:
      - ./images/proxy-socks-dante/conf/sockd.passwd:/home/danted/conf/sockd.passwd
    env_file:
      - .env
    ports:
      - "2020:2020"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dante.rule=HostRegexp(`${SERVER_CNAME_NAMESPACE}`, `{subdomain:[a-z]+}.${SERVER_CNAME_NAMESPACE}`)"
      - "traefik.http.routers.dante.entrypoints=dante"
      - "traefik.http.routers.dante.middlewares=authentik@docker"